# set "DOCKER_BUILDKIT=0" & docker-compose build
# docker run --rm -it id sh
# set "DOCKER_BUILDKIT=0" & docker build . -t angulon:nx-base
version: '3.8'

networks:
  corp:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: ./
      cache_from:
        - staijn/angulon:nx-base
      dockerfile: ./apps/api/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: staijn/angulon:api
    ports:
      - 7001:3333
    environment:
      NODE_ENV: 'development'
      PORT: 3333
    networks:
      - corp
    restart: on-failure

  website:
    container_name: website
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/website/Dockerfile
      args:
        NODE_ENV: 'development'
        BUILD_FLAG: ''
    image: staijn/angulon:website
    ports:
      - 7000:80
    environment:
      NODE_ENV: 'development'
      PORT: 4900
    networks:
      - corp
    restart: on-failure
