# set "DOCKER_BUILDKIT=0" & docker-compose build
# docker run --rm -it id sh
# set "DOCKER_BUILDKIT=0" & docker build . -t angulon:nx-base
version: '3.8'

networks:
  corp:
    driver: bridge

services:
  phos_api:
    depends_on:
      - phos_database
    container_name: phos_api
    build:
      context: ./
      cache_from:
        - staijn/angulon:nx-base
      dockerfile: ./apps/api/Dockerfile
    image: staijn/angulon:api
    ports:
      - 7001:3333
    environment:
      PORT: 3333
      DATABASE_HOST: phos_database
      DATABASE_DATABASE: phos
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: example
    networks:
      - corp
    restart: on-failure
    volumes:
      - /data/phos/api:/app/dist/apps/api/assets/config

  phos_website:
    container_name: phos_website
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/website/Dockerfile
    image: staijn/angulon:website
    ports:
      - 7000:80
    environment:
      PORT: 7000
    networks:
      - corp
    restart: on-failure

  phos_database:
    container_name: phos_database
    image: mariadb
    restart: always
    volumes:
      - /data/phos/database:/var/lib/mysql
    networks:
      - corp
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: phos
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
