# set "DOCKER_BUILDKIT=0" & docker-compose build
# docker run --rm -it id sh
# set "DOCKER_BUILDKIT=0" & docker build . -t angulon:nx-base
version: '3.8'

networks:
  corp:
    driver: bridge

services:
  angulon_api:
    container_name: angulon_api
    build:
      context: ./
      cache_from:
        - staijn/angulon:nx-base
      dockerfile: ./apps/api/Dockerfile
    image: staijn/angulon:api
    ports:
      - 7001:3333
    environment:
      PORT: 3333
    networks:
      - corp
    restart: on-failure
    volumes:
      - /data/angulon:/app/dist/apps/api/assets/config

  angulon_website:
    container_name: angulon_website
    build:
      context: ./
      cache_from:
        - nginx:1.19.2
      dockerfile: ./apps/website/Dockerfile
    image: staijn/angulon:website
    ports:
      - 7000:80
    environment:
      PORT: 7000
    networks:
      - corp
    restart: on-failure
