name: Build & Lint affected

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: npm i --legacy-peer-deps
      - run: npx nx workspace-lint
      - run: npx nx affected --target=build --parallel=3
      - run: npx nx affected --target=lint --parallel=3
  deploy:
    runs-on: ubuntu-latest
    name: Docker Deploy
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create custom buildx builder
        run: docker buildx create --name mybuilder
      - name: Use the created builder
        run: docker buildx use mybuilder
      - name: Bootstrap builder
        run: docker buildx inspect --bootstrap


      - name: Build and push base image
        run: docker buildx build --platform=linux/arm64/v8,linux/amd64 -t ${{ secrets.USERNAME }}/angulon:nx-base --push .
      - name: Build sub-application images
        run: docker buildx bake --push --set *.platform=linux/arm64/v8,linux/amd64
